/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcadotrevorfernandez;


import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.ImageIcon;

/**
 *
 * @author tfernandez_mecon
 */
public class ventanaAhorcado extends javax.swing.JFrame {
    private static final String SERIALIZED_FILE_NAME = "primeraDivision.xml";
    /**
     * Creates new form ventanaAhorcado
     */
    public ventanaAhorcado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    int contador;
    Scanner lector = new Scanner(System.in);
    String ingreso;

    
    //creo una lista con los equipos y trato de cargarlos de archivo, si no puedo creo el archivo y la lista
    List primeraDivision = new ArrayList();
    
    
    
    //seteo un equipo en la palabra a adivinar
    Palabra palabra = new Palabra();
    //palabra.setearPalabra(primeraDivision);
    
    //oculto la palabra a adivinar
    Palabra auxiliar = new Palabra();
    //String oculto = Palabra.ocultarPalabra(palabra.getPalabra());
    //Palabra oculto = new Palabra();
    //oculto.setPalabra(Palabra.ocultarPalabra(palabra.getPalabra()));
    String oculto;

    //agrego los espacios a la palabra oculta (si tiene)
    //oculto = palabra.decubrirLetra(" ", oculto, palabra.getPalabra());  
    //oculto.decubrirLetra(" ", oculto, palabra.getPalabra());
    //auxiliar = auxiliar.toLowerCase();
                
                             
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBox1.setText("A");
        jCheckBox1.setEnabled(false);
        jCheckBox1.setFocusable(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("B");
        jCheckBox2.setEnabled(false);
        jCheckBox2.setFocusable(false);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("C");
        jCheckBox3.setEnabled(false);
        jCheckBox3.setFocusable(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("D");
        jCheckBox4.setEnabled(false);
        jCheckBox4.setFocusable(false);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("E");
        jCheckBox5.setEnabled(false);
        jCheckBox5.setFocusable(false);
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("F");
        jCheckBox6.setEnabled(false);
        jCheckBox6.setFocusable(false);
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setText("G");
        jCheckBox7.setEnabled(false);
        jCheckBox7.setFocusable(false);
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setText("H");
        jCheckBox8.setEnabled(false);
        jCheckBox8.setFocusable(false);
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("I");
        jCheckBox9.setEnabled(false);
        jCheckBox9.setFocusable(false);
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setText("J");
        jCheckBox10.setEnabled(false);
        jCheckBox10.setFocusable(false);
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCheckBox11.setText("S");
        jCheckBox11.setEnabled(false);
        jCheckBox11.setFocusable(false);
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jCheckBox12.setText("R");
        jCheckBox12.setEnabled(false);
        jCheckBox12.setFocusable(false);
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jCheckBox13.setText("Q");
        jCheckBox13.setEnabled(false);
        jCheckBox13.setFocusable(false);
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jCheckBox14.setText("P");
        jCheckBox14.setEnabled(false);
        jCheckBox14.setFocusable(false);
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setText("O");
        jCheckBox15.setEnabled(false);
        jCheckBox15.setFocusable(false);
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        jCheckBox16.setText("Ñ");
        jCheckBox16.setEnabled(false);
        jCheckBox16.setFocusable(false);
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });

        jCheckBox17.setText("N");
        jCheckBox17.setEnabled(false);
        jCheckBox17.setFocusable(false);
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });

        jCheckBox18.setText("M");
        jCheckBox18.setEnabled(false);
        jCheckBox18.setFocusable(false);
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });

        jCheckBox19.setText("L");
        jCheckBox19.setEnabled(false);
        jCheckBox19.setFocusable(false);
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });

        jCheckBox20.setText("K");
        jCheckBox20.setEnabled(false);
        jCheckBox20.setFocusable(false);
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });

        jCheckBox21.setText("T");
        jCheckBox21.setEnabled(false);
        jCheckBox21.setFocusable(false);
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });

        jCheckBox22.setText("U");
        jCheckBox22.setEnabled(false);
        jCheckBox22.setFocusable(false);
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });

        jCheckBox23.setText("V");
        jCheckBox23.setEnabled(false);
        jCheckBox23.setFocusable(false);
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
            }
        });

        jCheckBox24.setText("W");
        jCheckBox24.setEnabled(false);
        jCheckBox24.setFocusable(false);
        jCheckBox24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox24ActionPerformed(evt);
            }
        });

        jCheckBox25.setText("X");
        jCheckBox25.setEnabled(false);
        jCheckBox25.setFocusable(false);
        jCheckBox25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox25ActionPerformed(evt);
            }
        });

        jCheckBox26.setText("Y");
        jCheckBox26.setEnabled(false);
        jCheckBox26.setFocusable(false);
        jCheckBox26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox26ActionPerformed(evt);
            }
        });

        jCheckBox27.setText("Z");
        jCheckBox27.setEnabled(false);
        jCheckBox27.setFocusable(false);
        jCheckBox27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox27ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(oculto);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" ");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcadotrevorfernandez/ahorcado0.jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(112, 315));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox20)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox19)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox2)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox21)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox22)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox23)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox24)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox25)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox26)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox3)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox4)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox6)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox5)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox9)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox7)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox18)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox17)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox16)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox15)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox14)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox13)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox12)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox8)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox10)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox13)
                                    .addComponent(jCheckBox14)
                                    .addComponent(jCheckBox15)
                                    .addComponent(jCheckBox16)
                                    .addComponent(jCheckBox17)
                                    .addComponent(jCheckBox18)
                                    .addComponent(jCheckBox19)
                                    .addComponent(jCheckBox20)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox8)
                                    .addComponent(jCheckBox10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox11)
                                    .addComponent(jCheckBox12))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox21)
                            .addComponent(jCheckBox22)
                            .addComponent(jCheckBox23)
                            .addComponent(jCheckBox24)
                            .addComponent(jCheckBox25)
                            .addComponent(jCheckBox26)
                            .addComponent(jCheckBox27))
                        .addGap(41, 41, 41))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        contador = 6;
        
        //cargo los equipos, si no existe el archivo genero la lista y el archivo
        primeraDivision = Club.deserializarClubes();

        //cargo una palabra para adivinar
        palabra.setearPalabra(primeraDivision);
        
        //creo un auxiliar donde voy a manipular la palabra (por ejemplo pasarla a minusculas)
        auxiliar.setPalabra((palabra.getPalabra()).toLowerCase());
        auxiliar.setAyuda(palabra.getAyuda());
        
        //oculto la palabra, le agrego los espacios y la mustro
        oculto = Palabra.ocultarPalabra(palabra.getPalabra());  
        oculto = palabra.decubrirLetra(" ", oculto, palabra.getPalabra());
        jLabel1.setText(oculto);
        
        //cambio el texto del boton de inicio, borro la label de ayuda y pongo la imagen en blanco
        jButton1.setText("Reiniciar");
        jLabel2.setText("");
        jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado0.jpg")));
        
        //habilito y saco tildes de los checkbox
        jCheckBox1.setEnabled(true);        
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);        
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);        
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);        
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);        
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);        
        jCheckBox12.setEnabled(true);
        jCheckBox13.setEnabled(true);        
        jCheckBox14.setEnabled(true);
        jCheckBox15.setEnabled(true);        
        jCheckBox16.setEnabled(true);
        jCheckBox17.setEnabled(true);        
        jCheckBox18.setEnabled(true);
        jCheckBox19.setEnabled(true);        
        jCheckBox20.setEnabled(true);
        jCheckBox21.setEnabled(true);        
        jCheckBox22.setEnabled(true);
        jCheckBox23.setEnabled(true);        
        jCheckBox24.setEnabled(true);
        jCheckBox25.setEnabled(true);        
        jCheckBox26.setEnabled(true);              
        jCheckBox27.setEnabled(true); 
        
        jCheckBox1.setSelected(false);        
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);        
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);        
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);        
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);        
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);        
        jCheckBox12.setSelected(false);
        jCheckBox13.setSelected(false);        
        jCheckBox14.setSelected(false);
        jCheckBox15.setSelected(false);        
        jCheckBox16.setSelected(false);
        jCheckBox17.setSelected(false);        
        jCheckBox18.setSelected(false);
        jCheckBox19.setSelected(false);        
        jCheckBox20.setSelected(false);
        jCheckBox21.setSelected(false);        
        jCheckBox22.setSelected(false);
        jCheckBox23.setSelected(false);        
        jCheckBox24.setSelected(false);
        jCheckBox25.setSelected(false);        
        jCheckBox26.setSelected(false);              
        jCheckBox27.setSelected(false);  
   }  
    
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        System.out.println("a");   
        ingreso = "a";
        jCheckBox1.setEnabled(false);        
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        System.out.println("b");
        ingreso = "b";
        jCheckBox2.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());            
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        System.out.println("c");
        ingreso = "c";
        jCheckBox3.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());            
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        System.out.println("d");
        ingreso = "d";
        jCheckBox4.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        System.out.println("e");
        ingreso = "e";
        jCheckBox5.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        System.out.println("f");
        ingreso = "f";
        jCheckBox6.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        System.out.println("g");
        ingreso = "g";
        jCheckBox7.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        System.out.println("h");
        ingreso = "h";
        jCheckBox8.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        System.out.println("i");
        ingreso = "i";
        jCheckBox9.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        System.out.println("j");
        ingreso = "j";
        jCheckBox10.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        System.out.println("s");
        ingreso = "s";
        jCheckBox11.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        System.out.println("r");
        ingreso = "r";
        jCheckBox12.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        System.out.println("q");
        ingreso = "q";
        jCheckBox13.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        System.out.println("p");
        ingreso = "p";
        jCheckBox14.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        System.out.println("o");
        ingreso = "o";
        jCheckBox15.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        System.out.println("ñ");
        ingreso = "ñ";
        jCheckBox16.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        System.out.println("n");
        ingreso = "n";
        jCheckBox17.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
        System.out.println("m");
        ingreso = "m";
        jCheckBox18.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
        System.out.println("l");
        ingreso = "l";
        jCheckBox19.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox19ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        System.out.println("k");
        ingreso = "k";
        jCheckBox20.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
        System.out.println("t");
        ingreso = "t";
        jCheckBox21.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox21ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        System.out.println("u");
        ingreso = "u";
        jCheckBox22.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox23ActionPerformed
        System.out.println("v");
        ingreso = "v";
        jCheckBox23.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox23ActionPerformed

    private void jCheckBox24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox24ActionPerformed
        System.out.println("w");
        ingreso = "w";
        jCheckBox24.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox24ActionPerformed

    private void jCheckBox25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox25ActionPerformed
        System.out.println("x");
        ingreso = "x";
        jCheckBox25.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox25ActionPerformed

    private void jCheckBox26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox26ActionPerformed
        System.out.println("y");
        ingreso = "y";
        jCheckBox26.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
        }
        jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
    }//GEN-LAST:event_jCheckBox26ActionPerformed

    private void jCheckBox27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox27ActionPerformed
        System.out.println("z");
        ingreso = "z";
        jCheckBox27.setEnabled(false);
        
        if((auxiliar.getPalabra()).contains(ingreso)){
            oculto = auxiliar.decubrirLetra(ingreso, oculto, auxiliar.getPalabra()); 
            jLabel1.setText(oculto);
            jLabel2.setText("Correcto!");
        }else{
            jLabel2.setText("Fallaste!");
            contador--;
        }
        
        if(!oculto.contains("*")){
            jLabel2.setText("GANASTE!, la palabra oculta era " + palabra.getPalabra());
            jLabel1.setText(palabra.getPalabra());
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource("/ahorcadotrevorfernandez/ahorcado7.jpg")));
            
        }else{
            if(contador==0){
                jLabel2.setText("GAME OVER");
                
            }
            if(contador == 1){
                jLabel2.setText("Último intento");
                jLabel2.setText("Pista: su cancha esta ubicada en " + auxiliar.getAyuda()+"\n");         
            }
            jLabel3.setIcon(new ImageIcon(jLabel3.getClass().getResource(palabra.stringImagen(contador))));
        }
    }//GEN-LAST:event_jCheckBox27ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaAhorcado().setVisible(true);
                }    
            }    
        ); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
